<template>
  <div class="relative">
    <UPageCard
      variant="subtle"
      class="rounded-2xl"
    >
      <video
        class="rounded-xl"
        data-v-baf90ddd=""
        preload="none"
        poster="/about.png"
        :controls="true"
      ><source
        data-v-baf90ddd=""
        src="/about.webm"
        type="video/webm"
      ><source
        data-v-baf90ddd=""
        src="/about.mp4"
        type="video/mp4"
      ><source
        data-v-baf90ddd=""
        src="/about.ogg"
        type="video/ogg"
      >
      </video>
    </UPageCard>
  </div>
</template>
